OgreWebBFFs/magic-league

Gemfile.lock
app.json
config/database.yml
db/seeds.rb

This is a small PR to change the database configuration to connect to the heroku pg database through env vars.

database config for prod

---

spec/service_objects/ranking_engine_spec.rb

reduce performance threshold in test 😭

---

app/controllers/home_controller.rb
app/views/home/index.html.erb

Provide default date and time values to the form inputs.

Home / index - Default match date and time added

---

app/assets/stylesheets/main-style.css
app/assets/stylesheets/main-style.less
app/views/rules/index.html.erb

Also mildly adjust Dashboard tables to match the copy cards.

Adding in Rules Copy and Static copy page styling

---

app/assets/stylesheets/main-style.css
app/assets/stylesheets/main-style.less
app/views/layouts/application.html.erb

Very small update, just adding ranking to the Nav, and adjusting how small screens handle the added nav element.

Adding Ranking page link

---

app/assets/stylesheets/main-style.css
app/assets/stylesheets/main-style.less
app/views/layouts/application.html.erb

Removing static width on menu, and adjusting display options to work in that new sitch

Fizing Mac broswer Nav Issues

---

app/assets/stylesheets/main-style.css
app/assets/stylesheets/main-style.less
app/views/collections/edit.html.erb
app/views/dashboard/index.html.erb

Howdy Babees, 
Adding in some styling to the buttons and inputs for the card grid currently used in collections.   
I am curious to see if Mac browser font stuff breaks anything .

Adding in grid and input stylings

---

app/views/collections/edit.html.erb

unbind click events before rebinding them

---

app/views/collections/edit.html.erb

Somehow we lost a few tidbits in a merge for the Add/Subtract buttons.  Added back in here

Adding back in stripped out class/icon

---

app/assets/stylesheets/main-style.css
app/assets/stylesheets/main-style.less
app/views/collections/edit.html.erb
app/views/dashboard/index.html.erb
app/views/layouts/application.html.erb

Minor styling updates to the Dash, and removal of the Decks area for the time being. 
Also a few minor updates to the footer slipped in, basically just adding a copyright section and a replacing the user email address with the user name.

Dashboard and Footer updates

---

app/assets/stylesheets/main-style.css
app/assets/stylesheets/main-style.less
app/views/collections/edit.html.erb
app/views/dashboard/_user_collections.html.erb
app/views/dashboard/_user_decks.html.erb
app/views/dashboard/index.html.erb
app/views/layouts/application.html.erb
app/views/users/show.html.erb

I think this wraps up all the little issues that popped up.

Css fixes after merge errors from pr 25

---

app/controllers/home_controller.rb
app/views/layouts/application.html.erb

This adds in some small JS scripts to grab date and time on the front end and put them into the match logger.  This avoids the time zone issues we had before.

JS Date and Time on Match Logger

---

app/assets/stylesheets/main-style.css
app/assets/stylesheets/main-style.less
app/assets/stylesheets/materialize.css
app/controllers/cards_controller.rb
app/views/cards/show.erb.html
app/views/cards/show.html.erb
app/views/collections/index.html.erb
app/views/collections/show.html.erb
app/views/devise/sessions/new.html.erb
app/views/layouts/application.html.erb
app/views/rules/index.html.erb
app/views/users/edit.html.erb
app/views/users/index.html.erb
config/routes.rb

Ready for merge if yall think its good.  
This is NOT a super polished page, but should be good for MVP

Adding a card profile view 

---

app/assets/stylesheets/main-style.css
app/assets/stylesheets/main-style.less
app/assets/stylesheets/materialize.css
app/views/collections/index.html.erb
app/views/collections/show.html.erb
app/views/devise/sessions/new.html.erb
app/views/layouts/application.html.erb
app/views/rules/index.html.erb
app/views/users/edit.html.erb
app/views/users/index.html.erb

Very simple stuff,  also edited the Roster to match, and condensed some Nav elements (including the Collections)  to a 'League' drop down.  That title, League, isn't hard and fast in my mind, just off the top of my head.

Added in Collections Page Styles

---

app/assets/stylesheets/main-style.css
app/assets/stylesheets/main-style.less
app/views/home/index.html.erb
app/views/layouts/application.html.erb

I went in to get the styling set up for Dustin to edit the views, but then I saw how easy it was to do so I just knocked this task out.  
That said, i certainly could have gotten some stuff wrong/not optimal. 
So please check:
- Ranking page names link to user show (Profiles) 
-Profile link in nav links to current user not Dashboard (the look was identical, but wanted to just store it in one place)
Note: the admin rights still will cause problems for non-admins viewing other users shows

Making ranking names links to user profiles

---

app/assets/stylesheets/main-style.css
app/assets/stylesheets/main-style.less
app/controllers/trades_controller.rb
app/views/collections/edit.html.erb
app/views/trades/index.html.erb

This only affects the edit collection view.  
MVP Goal for these toggles:
In a card grid: 
Any time you see a card, it has a wishlist toggle, 
Any time you see a card you own it has the for-trade toggle

Adding in trade check boxes on card view

---

app/helpers/application_helper.rb

ruby array indexes start at zero

---

app/assets/stylesheets/main-style.css
app/assets/stylesheets/main-style.less

change dropdown positioning from left: -50% to right: -10px

---

app/assets/stylesheets/main-style.css
app/assets/stylesheets/main-style.less
app/helpers/application_helper.rb
app/views/devise/shared/_links.html.erb

fix and prettify the google oauth button in devise views

---

app/assets/stylesheets/main-style.css
app/assets/stylesheets/main-style.less
app/controllers/wishlists_controller.rb
app/views/collections/show.html.erb
app/views/layouts/application.html.erb
app/views/wishlists/index.html.erb
app/views/wishlists/show.html.erb
config/routes.rb

I have pulled in the branch from [pr 63](https://github.com/OgreWebBros/magic-league/pull/63) into this branch to test the top button functionality between collections/wishlists

Creating a wishlist card grid view

---

app/assets/stylesheets/main-style.css
app/assets/stylesheets/main-style.less
app/views/layouts/application.html.erb

Added an onload function to the body that closes any open alerts after 5 seconds.
Currently there are no urgent alerts, but if one gets passed the urgent class it is Red rather than Orange.  Eventually we will want to adjust the onload to NOT target anything marked with the class urgent.  But that is a later thing.

Adds urgent class for alerts, auto removes all alerts after 5 seconds

---

app/assets/stylesheets/main-style.css
app/assets/stylesheets/main-style.less
app/controllers/matches_controller.rb
app/models/match.rb
app/views/layouts/application.html.erb
app/views/matches/index.html.erb
config/routes.rb

Accessible from the League drop down.  
Currently, just lists all matches, eventually users will be able to delete matches made in error.

Adding in a Match History

---

app/controllers/json_application_controller.rb
app/controllers/tradables_controller.rb
app/controllers/users_controller.rb
app/helpers/users_helper.rb
app/models/card.rb
app/models/tradable.rb
app/models/user.rb
app/policies/tradable_policy.rb
app/views/dashboard/_user_collections.html.erb
config/locales/en.yml
config/routes.rb
db/migrate/20181019174302_create_tradables.rb
db/schema.rb

did this over the weekend. Should get us most of the way to marking cards as tradable. Currently, you can still click the "mark as tradable" button on other user's profiles, but the server-side policy only allow modifying your own trades. Before this is merged, I will make those buttons unclickable, I just wanted to get an early PR for you all to review.

a user can mark their own cards as tradable

---

app/views/dashboard/_user_wishlist.html.erb

This just hides the button, which didnt really work anyway.
I did it with a fairly unthoughtful if/else.  There is certainly a better way to do this when we start to polish things up.

Adding in temp patch to hide button on non-current user

---

app/views/layouts/application.html.erb

This only fixes FF.  
App is still unusable in IE untill we sort out our JS better.

Changing event prop script to vanilla js syntax

---

app/assets/stylesheets/main-style.css
app/assets/stylesheets/main-style.less

Updating rankings display to work on Galaxy s5

---

app/views/layouts/application.html.erb

Link change

---

app/assets/javascripts/app_layout.js
app/assets/javascripts/application.js
app/assets/javascripts/helpers.js
app/views/dashboard/_user_collections.html.erb
app/views/layouts/application.html.erb
app/views/trades/index.html.erb

This is the initial round of placing javascript into separate modules/namespaces.  This is focused on the application layout page, and toggling elements (idedElementToggle renamed to toggleElementById, and moved to a generic Helpers module as opposed to being contained in the AppLayout module).

JS Modules Round 1

---

app/models/received_trade.rb
app/models/user.rb

Quickfix for updating number of trades allowed with the current poor implementation.  Now also determining extra trades for the users that get them.

ReceivedTrade - Jan quickfix

---

app/assets/javascripts/constants.js
app/views/collections/edit.html.erb
app/views/trades/index.html.erb

- added minimum search length to address issues related to some async requests returning later than expected.
- reset card grid state only when entire search has been cleared

Card Search - Trade and Collection Quickfix

---

app/models/received_trade.rb

Updated trade allowances for Feb still with hard coded values 😬

Trades - updated trade allowances for feb

---

app/assets/stylesheets/main-style.css
app/assets/stylesheets/main-style.less
app/controllers/matches_controller.rb
app/views/matches/index.html.erb

This styling is temporary, future plan is to break it down by month.

Updating Match order, and how the match table is styled.

---

app/models/received_trade.rb

Yet another update to the hard coded values for trade allowances...

Trades - updated trade allowances for March

---

app/models/received_trade.rb

This is now for June.  The extra trade set names aren't fully up to date, but I can follow up with that later.

Received Trade - updated number of trade sets

---

README.md

Changed the steps for setup, and removed all docker references.

Updating initial setup

---

app/views/rules/index.html.erb

New rules added, and a TON of typos corrected

---

app/models/received_trade.rb

Trades allowed updated for Sept

received trades - updated trades allowed

---

app/assets/stylesheets/main-style.css
app/assets/stylesheets/main-style.less
app/views/admin/users/index.html.erb

This PR also reminds me how crappy our styles are!  I need to refactor the whole bunch of them.

Adding styles for admin view

---

app/assets/javascripts/admin/settings.js
app/assets/stylesheets/admin/settings.scss
app/assets/stylesheets/main-style.css
app/assets/stylesheets/main-style.less
app/controllers/admin/matches_controller.rb
app/controllers/admin/settings_controller.rb
app/controllers/admin/users_controller.rb
app/helpers/admin/settings_helper.rb
app/models/setting.rb
app/policies/match_policy.rb
app/policies/setting_policy.rb
app/policies/user_policy.rb
app/views/admin/matches/_form.html.erb
app/views/admin/matches/_matches.html.erb
app/views/admin/matches/edit.html.erb
app/views/admin/matches/index.html.erb
app/views/admin/settings/edit.html.erb
app/views/admin/settings/update.html.erb
app/views/admin/users/index.html.erb
app/views/layouts/application.html.erb
config/routes.rb
db/migrate/20191028124153_remove_ranking_from_user.rb
db/migrate/20191028183522_create_settings.rb
db/schema.rb
db/seeds.rb
test/controllers/admin/settings_controller_test.rb

General Bugfixes
- fixes issue with lock/unlock logic on user admin page
- fixes issue with policies getting checked after actions are taken on admin user
Additions
- added navigation links to admin section
- added admin match section
- updated seed files to unlock users and have matches by default

Admin section

---

app/assets/stylesheets/main-style.css
app/assets/stylesheets/main-style.less
app/controllers/admin/settings_controller.rb
app/models/received_trade.rb
app/views/admin/settings/edit.html.erb
config/routes.rb
db/migrate/20200125211454_rename_trade_allowance_period_to_base_trade_sets.rb
db/schema.rb

Work in progress for editing league settings.  Currently only 'trade allowance period' which I've used as the number of trade sets applied to all users before bonus sets.

Admin - settings - add ability to update trade allowance value

---

README.md
package.json

Simple Readme update with set up instructions for Windows, and adding start scripts

Updating readme for Windows set up, adding start scripts

---

app/views/collections/edit.html.erb

fix: decrementor bug in collections edit

---

app/assets/stylesheets/card-grid/card-grid.scss
app/assets/stylesheets/dashboard/dashboard.scss
app/assets/stylesheets/sitewide/color-library.scss
app/assets/stylesheets/sitewide/sitewide.scss
app/javascript/components/Button/button.scss
app/javascript/components/CardGrid/WishlistToggle.jsx
app/javascript/components/Dashboard/Collection/Collection.jsx
app/javascript/components/Dashboard/Wishlist/RemoveWish.jsx
app/javascript/components/Dashboard/Wishlist/Wishlist.jsx
app/javascript/components/Dashboard/index.js
app/javascript/contexts/WishlistContext/index.jsx
yarn.lock

fix for wishlist toggle rendering on other's collections

---

app/assets/stylesheets/rankings/rankings.scss
app/controllers/home_controller.rb
app/javascript/components/Rankings/index.js
app/views/home/index.html.erb
yarn.lock

Sets up the rankings page
Adds the classNames package 
-https://www.npmjs.com/package/classnames
##Scope

feat: reactify rankings

---

app/javascript/components/CardBrowser/index.jsx
app/javascript/components/Dashboard/Wishlist/RemoveWish.jsx
app/views/trades/index.html.erb

ensure currentUserWishlist is being updated across pages

---

app/assets/javascripts/app_layout.js
app/assets/stylesheets/rankings/rankings.scss
app/assets/stylesheets/sitewide/animations.scss
app/assets/stylesheets/sitewide/cycling-background.scss
app/javascript/components/Button/button.scss
app/javascript/components/CyclingBackground/index.js
app/javascript/components/Dashboard/Collection/Collection.jsx
app/javascript/components/Dashboard/index.js
app/javascript/components/Rankings/index.js
app/views/home/index.html.erb
app/views/layouts/application.html.erb

fixes: clean up console errors about keys in dashboard, fixes z-indexing on rankings 
feats: componentes rotating background, and hide ranking easteregg
##Scope

feat: Cycling component, and hide rankings

---

app/javascript/components/Dashboard/ActionBar/EditAction.jsx
app/javascript/components/Dashboard/index.jsx
app/views/users/show.html.erb

fix: utilize collection id for edit page parameter

---

app/assets/stylesheets/rankings/rankings.scss
app/assets/stylesheets/sitewide/animations.scss
app/javascript/components/Rankings/index.js

- cleans up old rankings styles
- fixes rankings page overflow issues
##Scope
Rankings page

Fix rankings styles

---

app/controllers/home_controller.rb
app/controllers/matches_controller.rb
app/javascript/components/Navigation/MatchLogger/HeadToHeadLogger.jsx
app/javascript/components/Navigation/MatchLogger/MultiplayerLogger.jsx
app/javascript/components/Navigation/MatchLogger/MultiplayerLogger/PlacementSelector.jsx
app/javascript/components/Navigation/MatchLogger/MultiplayerLogger/index.jsx
app/javascript/components/Navigation/MatchLogger/index.jsx
app/javascript/components/Navigation/PlayerSelect/index.jsx
app/javascript/components/ToggleSwitch/index.jsx
app/javascript/packs/application.scss
app/javascript/stylesheets/navigation/match-logger.scss
app/javascript/stylesheets/navigation/navigation.scss
app/javascript/stylesheets/navigation/trade-logger.scss
app/javascript/stylesheets/sitewide/sitewide.scss
app/javascript/stylesheets/sitewide/toggle-switch.scss
app/service_objects/player_ranker.rb
db/migrate/20220604133856_add_event_id_to_matches.rb
db/schema.rb

New:
- Toggle between Season/Event match logging
- Event logging which utilizes multiplayer selection for results
- Filtering homepage standings and rankings based on event
Modified
- Form submission format for match logging
- Match create functionality to conform to multiplayer event logging
- Schema for matches to include event id
I specifically haven't created any Event object in database yet. I think that will come... but for now I'm focused on getting this system in place in short-order simply for the start of the Baldur's Gate event.
##Scope
Match Logging

feat: multiplayer match logging; event specific match logging

---

app/javascript/components/Navigation/MatchLogger/HeadToHeadLogger.jsx
app/javascript/components/Navigation/MatchLogger/index.jsx

Changed so the date picker defaults properly. Also added some basic form validation to prevent errors in the future.
##Scope
Match logging

fix default date logic. add basic form validation

---

Procfile

added Procfile as recommended by Heroku to use puma web server.  Using a sample command before moving to the puma config file.
##Scope
Web server

added Procfile as recommended by Heroku to use puma web server.

---

app.json

app.json - update postdeploy commands from rake to rails
##Scope
Update postdeploy commands in app.json from rake to rails commands since that's the current way to run those commands.  This is used when using heroku's review app feature.

app.json - update postdeploy commands from rake to rails

---

app.json

app.json - add stack entry with value "heroku-22"
##Scope
Build process.  Review apps should use the stack entry to specify the stack it's using.

app.json - add stack entry with value "heroku-22"

---

app/views/users/_admin_fields.html.erb

use proper redirect uri for admin edit pages

---

app/javascript/components/CardOwnership/OwnershipTable.jsx
app/javascript/stylesheets/cards/card-profile.scss

A couple small changes on card profile page:
- owner names are now links
- removed card image order: 2 for smaller screens
##Scope
Card details / profile page

card profile tweaks

---

app/javascript/components/UserDisplay/Dashboard/Trades/TradeReviewButton/TradeReview.jsx

Quick class swap for the accept/decline button colors on the accept trade review screen.
##Scope
Trade Review

fix: color swap on trade buttons

---

app/controllers/matches_controller.rb
app/javascript/components/Navigation/MatchLogger/HeadToHeadLogger.jsx

fix timezone reporting for matches

---

app/javascript/components/Navigation/MatchLogger/HeadToHeadLogger.jsx

use browser date/time for default in logger

---

Gemfile
Gemfile.lock
app/controllers/admin/matches_controller.rb
app/controllers/matches_controller.rb
app/javascript/components/Matches/Paginator.jsx
app/javascript/components/Matches/index.jsx
app/javascript/stylesheets/match-listings/matches-table.scss
app/javascript/stylesheets/match-listings/paginator.scss
app/views/admin/matches/index.html.erb
app/views/matches/index.html.erb
db/seeds.rb

matches pagination

---

app/bot/ogre_bot.rb
app/bot/trade_alerts.rb
app/controllers/matches_controller.rb
app/controllers/trades_controller.rb
app/javascript/components/UserDisplay/Dashboard/Trades/StatusAction.jsx
app/javascript/stylesheets/dashboard/trades.scss
app/models/trade.rb
config/shakapacker.yml

Bot trade alerts

---

app/models/card.rb
config/the_list_cards.txt
db/seeds.rb
lib/tasks/get_cards.rake

Cards populate updates

---

Gemfile
Gemfile.lock
app/bot/announcements_access.rb
app/bot/ogre_bot.rb
app/controllers/announcements_controller.rb
app/controllers/hello_world_controller.rb
app/controllers/home_controller.rb
app/javascript/components/Announcements/index.jsx
app/javascript/components/Navigation/DesktopNav/index.jsx
app/javascript/components/Navigation/MobileNav/index.jsx
app/javascript/components/Navigation/index.jsx
app/javascript/packs/application.scss
app/javascript/stylesheets/announcements/announcements.scss
app/javascript/stylesheets/navigation/navigation.scss
app/models/user.rb
app/service_objects/render_message.rb
app/views/announcements/index.html.erb
app/views/hello_world/index.html.erb
app/views/home/index.html.erb
app/views/layouts/application.html.erb
config/application.rb
config/environments/development.rb
config/environments/production.rb
config/routes.rb

Announcements page

---

app/controllers/admin/matches_controller.rb

reset cache on delete match

---

app/javascript/components/Login/index.jsx
app/javascript/components/Matches/index.jsx
app/javascript/components/Rankings/index.jsx
app/javascript/components/UserDisplay/Dashboard/ActionBar/EditAction.jsx
app/javascript/components/UserDisplay/Dashboard/ActionBar/FilterAction/index.jsx
app/javascript/components/UserDisplay/Dashboard/ActionBar/ViewToggle.jsx
app/javascript/components/UserDisplay/index.jsx
app/javascript/helpers/hooks/use-theme.js
app/javascript/stylesheets/dashboard/dashboard.scss
app/javascript/stylesheets/form/edit_user.scss
app/javascript/stylesheets/login/login.scss
app/javascript/stylesheets/navigation/navigation.scss
app/javascript/stylesheets/rankings/rankings.scss
app/javascript/stylesheets/sitewide/animations.scss
app/javascript/stylesheets/sitewide/color-library.scss
app/javascript/stylesheets/sitewide/sitewide.scss
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/users/edit.html.erb

- theme text brightness uped
- dashboard action buttons now theme colors
- upped the fill lightness on all themes but Ms.White and C. Mustard
- section padding fixed
- incrementor hover is half fixed 
- paint brush moved
- made page headers all h1
##Scope

fix: tw review callouts 

---

app/controllers/home_controller.rb
app/javascript/components/UserDisplay/Dashboard/Trades/TradeReviewButton/TradeReview.jsx

-modal typo 
-filter unranked users 
##Scope

Updates per review session

---

app/bot/ogre_bot.rb
app/bot/trade_alerts.rb
app/controllers/trades_controller.rb
app/javascript/components/UserDisplay/Dashboard/Trades/TradeReviewButton/TradeReview.jsx
app/javascript/components/UserDisplay/Dashboard/Trades/TradeReviewButton/post-trade-review.js

pm functionality checks for user existance first

---

app/javascript/components/UserDisplay/Dashboard/ActionBar/FilterAction/index.jsx
app/javascript/stylesheets/navigation/navigation.scss

Drop down fix

---

app/bot/trade_alerts.rb

fix from user receiving to msg on trade error

---

app/javascript/components/UserDisplay/Dashboard/ActionBar/ActionBar.jsx
app/javascript/components/UserDisplay/Dashboard/Collection/CallToAction.jsx
app/javascript/components/UserDisplay/Dashboard/Collection/index.jsx
app/javascript/components/UserDisplay/Dashboard/EmptyState/index.jsx
app/javascript/components/UserDisplay/Dashboard/Trades/index.jsx
app/javascript/components/UserDisplay/Dashboard/Wishlist/index.jsx
app/javascript/stylesheets/dashboard/dashboard.scss

- fixes jittery action button (filter/edit etc)
- just a magic number value for now.  have to rework icon only buttons a bit  
- fixes empty state on collection
- does not render action bar on Trades
##Scope

fix: dashboard buttons

---

app/javascript/components/Rankings/index.jsx
app/javascript/stylesheets/draffle/draffle.scss
app/javascript/stylesheets/rankings/rankings.scss

- rankings wrapper to better calc its height relative to page
##Scope

style: rankings update

---

app/controllers/home_controller.rb
app/controllers/matches_controller.rb

use Time object instead of DateTime to respect rails config timezone

---

app/bot/announcements_access.rb
app/controllers/announcements_controller.rb
app/controllers/application_controller.rb
app/javascript/components/Navigation/index.jsx
app/views/layouts/application.html.erb

user cookies to hide announcements notification if it's been viewed

---

app/javascript/components/AdvancedSearch/SetsPicker.jsx

update symbol map in advanced card browser

---

app/helpers/prints_helper.rb
app/javascript/components/CardGrid/CardImage.jsx
app/javascript/components/CardGrid/CardImageLink.jsx
app/javascript/components/CardOwnership/index.jsx
app/javascript/components/Draffles/DraffleEdit/EditPrizes/Divider.jsx
app/javascript/stylesheets/card-grid/card-grid.scss
app/models/card.rb
app/serializers/card_serializer.rb
db/migrate/20240531155501_add_back_image_url_to_cards.rb
db/schema.rb
package.json
yarn.lock

Flip cards

---

lib/tasks/get_cards.rake

add ability to populate single cards and ranges

---

app/javascript/components/AdvancedSearch/SetsPicker.jsx

update sets picker for MH3 and M3C

---

app/javascript/components/UserDisplay/Dashboard/ActionBar/FilterAction/filter-configs/color.jsx
app/models/card.rb

use color identity to identify card color in db

---

Gemfile
Gemfile.lock

update discordrb to most recent changes for API fix

---

app/models/user.rb
config/initializers/devise.rb

timeoutable - remove usage of this setting
rememberable - enable secure cookie option in prod env
##Scope
User, config

remove timeoutable, update rememberable option

---

app/javascript/components/AdvancedSearch/SetsPicker.jsx

update sets picker

---

app/bot/trade_request.rb

fix misspelling in bot trade request message

---

app/controllers/trades_controller.rb
app/models/user.rb

check quantity for trade invenotry validation

---

app/controllers/cards_controller.rb
app/controllers/trade_message_controller.rb
app/controllers/users_controller.rb
app/javascript/components/CardOwnership/OwnershipTable.jsx
app/javascript/components/CardOwnership/index.jsx
app/javascript/components/Icons/ResendMessageIcon.jsx
app/javascript/components/TradeProposal/TradeProposalButton.jsx
app/javascript/components/TradeProposal/TradeProposalModal.jsx
app/javascript/components/UserDisplay/Dashboard/Collection/index.jsx
app/javascript/components/UserDisplay/index.jsx
app/javascript/stylesheets/draffle/loader.scss
app/javascript/stylesheets/sitewide/button.scss
app/javascript/stylesheets/sitewide/modal.scss
app/models/card.rb
app/models/message_status.rb
app/models/user.rb
app/views/cards/show.html.erb
app/views/users/show.html.erb
db/migrate/20240831175110_create_message_statuses.rb
db/schema.rb

Message tracking

---

app/controllers/trade_message_controller.rb
app/javascript/components/Draffles/LoadingTakeOver.jsx
app/javascript/components/Icons/LoadingIcon.jsx
app/javascript/components/TradeProposal/TradeProposalModal.jsx
app/javascript/components/UserDisplay/Dashboard/index.jsx
app/javascript/helpers/scroll-restoration/index.js
app/javascript/stylesheets/draffle/loader.scss
app/javascript/stylesheets/global.scss
app/javascript/stylesheets/sitewide/trade-message.scss

Message tracking update

---

app/javascript/components/TradeProposal/TradeProposalModal.jsx

fix refresh on close trade modal

---

app/javascript/components/TradeProposal/TradeProposalModal.jsx

replace refreshPage function for trade modal closing

---

app/controllers/application_controller.rb
app/javascript/stylesheets/sitewide/color-library.scss
app/service_objects/user_device.rb
app/views/layouts/application.html.erb

detect safari devices server-side

---

app/javascript/components/UserDisplay/Dashboard/Trades/index.jsx
app/javascript/stylesheets/dashboard/trades.scss
app/javascript/stylesheets/match-listings/matches-table.scss

fix some mobile styling for trades and matches displays

---

app/workers/autodraft.rb

set autodraft to 90 seconds for quick-pick round
