- app/controllers/received_trades_controller.rb
- app/models/received_trade.rb
- app/models/user.rb
- app/views/dashboard/_user_trades.html.erb
- config/routes.rb
- db/migrate/20181103182705_create_received_trades.rb
- db/schema.rb
First draft functionality of tracking number of cards received in trade.
In the user dashboard, the request is sent when the input generates a change event.  I've been triggering this by pressing enter after inputting a new value or using the up and down buttons provided by the browser for input number type.
One shouldn't be able to change the values of other users' dashboards, and this is currently only prevented in the front end by disabling the input.  No server side authorization is done for that, but should be done as a follow up to do item.
> Received Trades -  first draft functionality

- app/models/received_trade.rb
- app/models/user.rb
This is the first step to remove hard coding for determining the amount of trade sets a user has.  Will use the Settings table's values for trade_allowance_period and bonus_trade_users when calculating the total amount of trade sets.
> Trades allowed dec 2019

- app/assets/stylesheets/rankings/rankings.scss
- app/views/home/index.html.erb
Several changes to the rankings layout as per James' prototypes.  These are mostly to make better use of screen real estate and establish more solid landmarks on the rankings buttons.  
When reviewing please check these against the prototypes in discord (they will mostly match the new layout), and also check at small screen sizes (chrome emulator iphone 5e is what I used as the smallest screen we care about)
> Rankings layout update

- app/assets/javascripts/app_layout.js
- app/assets/javascripts/helpers.js
- app/assets/stylesheets/card-grid/card-grid.scss
- app/assets/stylesheets/dashboard/dashboard.scss
- app/assets/stylesheets/login/login.scss
- app/assets/stylesheets/sitewide/alert.scss
- app/assets/stylesheets/sitewide/modal.scss
- app/assets/stylesheets/sitewide/sitewide.scss
- app/views/dashboard/_user_collections.html.erb
- app/views/dashboard/_user_wishlist.html.erb
- app/views/home/index.html.erb
- app/views/layouts/application.html.erb
- app/views/trades/index.html.erb
- app/views/users/show.html.erb
- package.json
This pull takes our existing Dashboard and starts integrating some of the new layout ideas. Specifically, it sets up a tab-able container that houses our wishlist and collection tables.  Eventually, this will be the container that will display the card grid views for those same lists.  
This PR adds font awesome icons, to better deal with mobile special character display issues.
This does not add any functionality for the user, aside from quick link to the trades page where they can wishlist cards. 
Profile pages 
Several areas of the site were refactored to work with the font-awesome icons, and new global checkbox styles, including: 
- log in screen stay logged in checkbox
- modal / match logger close button
- card grid wish list toggles
> Initial unified profile page card interface

- app/assets/javascripts/app_layout.js
AppLayout - setMatchDateAndTime - fix for issue when using toISOString (it uses UTC, which can cause the date to be a day in the future)
The date generated for use in the Log Match form could be a date 1 day in the future.  The cause for this is that the toISOString method will convert the date to UTC, which was unintended.  This is now generating the date string using other methods on the date object and then constructing the string with those parts.
##Scope
Log Match form.
> Log Match date fix

- app/controllers/cards_controller.rb
- app/models/card.rb
- db/migrate/20200802225446_add_data_to_cards.rb
- db/schema.rb
- lib/tasks/get_cards.rake
Migration and Schema - added fields to cards
Card - added scopes to query the new text fields and all text
Cards Controller - Now querying all game text on the card
New data fields have been added to the cards table schema.  The card search functionality of the site will now search all of the game text associated with the card.  These fields are name, type_line, and oracle_text (which is the main block of rules text on a card).
Other fields were also brought in to facilitate future updates where we can further develop card filtering or display information card lists.
##Scope
> Card text search update

- lib/tasks/get_cards.rake
This is a fix for the get_cards rake task when setting the image_url for multi-faced cards.  Currently it errors out since it tries to access a property that doesn't exist when the card has multiple card faces.  This tests whether a card has a card_faces property and then will get the first of those images.
##Scope
Card table population rake task
> get_cards - fix for setting multi-faced cards' image_url

- app/javascript/components/CardBrowser/TradeProposalModal.jsx
- app/javascript/components/Modal/index.jsx
Prior to this update, the card grid would reset when you closed the trade proposal modal in browse cards view. This annoyed me greatly. So I fixed it.
The fix was really just to remove the `href="#"` from the button but, in trying to figure out what this bug was, I created a reusable modal that is more reusable and follows proper portal patterns. So, you're welcome.
##Scope
> Fix: browse modal interaction

- config/initializers/devise.rb
#196 from @james-tw 
##Scope
Devise login timeout
> Overwrite default timeout to keep users signed in for 1 year

- app/javascript/components/Dashboard/index.jsx
- app/javascript/helpers/scroll-restoration/index.js
- app/javascript/packs/application.js
Turbolinks and react do not play nicely together. So, I had to hamfist a solution to maintain scrolling on the card grid. This is probably the only area we will run into this problem for now.
##Scope
> feat: card grid scroll restoration

- app/javascript/components/Navigation/MatchLogger/index.jsx
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString#using_options
##Scope
> fix: match logger ios expects only hours and minutes

- Gemfile
- Gemfile.lock
- config/webpack/environment.js
- package.json
- postcss.config.js
- yarn.lock
Setup webpack to compile using postcss8 in order to incorporate plugin to support custom properties.
To test: run `NODE_ENV=production bin/webpack` to compile assets in production mode. This command currently fails on `main` branch and is preventing us from deploying to our environments.
##Scope
> fix: setup webpacker to compile custom css properties

- app/controllers/matches_controller.rb
- app/models/match.rb
- app/models/result.rb
- app/service_objects/player_ranker.rb
- app/service_objects/ranking_engine.rb
- db/migrate/20220530144839_create_matches_and_results_relationship.rb
- db/schema.rb
- db/seeds.rb
- spec/models/result_spec.rb
- spec/service_objects/player_ranker_spec.rb
- spec/service_objects/ranking_engine_spec.rb
Currently, our matches are logged with only a single winner and loser id associated to the match. This PR modifies that model so that a match can contain any number of participants that each receive a "place" in the match. Moving to this model will help us support multiplayer matches in the future for different events or different game types.
##Scope
Match Logging
Ranking
> chore: multiplayer db setup

- app/javascript/components/Navigation/index.jsx
Menu 'Contact Us' menu doesn't work as expected.  Removing for now, as it tries to route to a mailto link href
##Scope
Navigation
> Menu 'Contact' item doesn't work as expected.  Removing for now

- config/initializers/new_framework_defaults_6_0.rb
Rails 6.0 - enabling the rest of the new framework defaults
When this is deployed and can be verified it doesn't break existing functionality, we can fully switch over to the new framework defaults
##Scope
Config
> Rails 6.0 - enabling the rest of the new framework defaults

- app/javascript/components/TradeProposal/TradeProposalModal.jsx
TradeProposalModal - fixed use case when attempting to send one person a trade email
The issue was that when attempting to send one user an email, the user_id form hidden input was not set.  So on the controller side it always thought it should send to everyone with the card since it didn't receive a user_id parameter.  This is more of a quick fix, but I feel the trade modals can and should be more explicit for what they're attempting to do in the props they're passing instead of inferring from the users attached to the card prop.
##Scope
TradeProposalModal
> TradeProposalModal - fixed use case when contacting one user

- app/controllers/application_controller.rb
application_controller - made Pundit include more specific per deprecation warning
##Scope
Authorization.  I noticed deprecation warnings in my local env about how Pundit was included and it should be Pundit::Authorization instead.
> application_controller - made Pundit include more specific per deprecation warning

- Gemfile
- Gemfile.lock
- config/initializers/new_framework_defaults_6_1.rb
new_framework_defaults_6_1 - Uncommented all new defaults
Gemfile - added image_processing since one of the new defaults is related.  This is required when doing image transformation, which we may want to consider starting to do
##Scope
Configuration.  Adding the image_processing gem may be unnecessary, but will be useful if we starting doing transformations on images.  We may want to consider doing so since we load a lot of images at times, though I'm unsure this would have an effect since those are external API calls?  Though with the background images that we use, it could be good to be doing some transformations on them to save bandwidth / optimize.
Even if not required, this shouldn't be much/any overhead to include and not use.
> new_framework_defaults_6_1 - Uncommented all new defaults

- app/controllers/cards_controller.rb
- app/javascript/components/CardOwnership/OwnershipTable.jsx
- app/javascript/components/CardOwnership/WishlistTable.jsx
- app/javascript/components/CardOwnership/index.jsx
- app/javascript/stylesheets/cards/card-profile.scss
- app/views/cards/show.html.erb
card - show: slightly modified to sort names and add info to wishlisters_details for display
CardOwnership: updated to also show wishlisters, slightly modified existing elements
Added table on card show/profile page to also show the users who have wishlisted the card.  Minor update to the owners table.
##Scope
card show action, CardOwnership files
> CardOwnership - add wishlisters table

- app/javascript/stylesheets/card-grid/card-grid.scss
Noticed that the black text in the card quantity updater was not contrasted enough. Changed it to be neutral coloring
Before Changes:
After Changes:
##Scope
> make quantity selector text color neutral

- app/controllers/users/omniauth_callbacks_controller.rb
- app/models/user.rb
- config/initializers/devise.rb
remember_me - enable this behavior when logging in via omniauth
user - add timeoutable to unlock functionality of the timeout_in config value
Timeoutable - this attribute is required on the user model in order to enable the 'timeout_in' devise config value.  Setting this to a day as those who log in by standard username and password have a remember me checkbox that functions.  So if someone wants to opt out that way they can, but still won't have to log in multiple times per league day
Omniauth remember_me - this will enable remember_me behavior when using omniauth.  Important to note that there's no way to opt out of it here.  If one logs off it will reset the remember_created_at in the db.
As far as why remember_me can't be toggled with the checkbox: …
> Remember me and timeout update

- config/environments/production.rb
Uncommenting out config.force_ssl option in production.rb
##Scope
Production config
> production.rb - uncomment config.force_ssl option

- app/javascript/stylesheets/sitewide/button.scss
Updates the Buttons to use neutral-text-color (white), and setting the disabled buttons to use inverse-text-color(black)
> style(Button): udpate text colors

- app/javascript/stylesheets/footer/footer.scss
- app/javascript/stylesheets/navigation/navigation.scss
- app/javascript/stylesheets/rankings/rankings.scss
- app/javascript/stylesheets/sitewide/button.scss
- app/javascript/stylesheets/sitewide/color-library.scss
- yarn.lock
Safari calc values require % appender and chrome requires only the numeral and no %.  So here we set up some cheesy media queries to update these values based on browser
##Scope
colors on nav, buttons, rankings, footer
> fix: safari color updates

- app/javascript/stylesheets/sitewide/color-library.scss
bringing highlight color to follow the other color updates for safari
##Scope
> fix(highlight-color): update highlight color for safari
